Add assertions for no messages
docomoinnovations/drupalextension pull request #5
Opened 2022-03-24 00:49 UTC by kumikoono

To assert no error/warning messages visible

2022-03-29 17:51 UTC, onotmil commented
It looks good to me.

2022-03-31 08:18 UTC, naoi requested changes

2022-03-31 08:18 UTC, naoi commented on src/Drupal/DrupalExtension/Context/MessageContext.php
> +    $this->assertNotVisible($selector_id);
@kumikoono This should be:

```suggestion
  public function assertSelectorNotVisible($selector): void {

    $selector_id = 'warning_message_selector';

    if ($selector == 'success') {
      $selector_id = 'success_message_selector';
    }

    if (selector == 'error') {
      $selector_id = 'error_message_selector';
    }

    $this->assertNotVisible($selector_id);
```

2022-03-31 08:18 UTC, naoi commented on src/Drupal/DrupalExtension/Context/MessageContext.php
> +  public function assertErrorWarningNotVisible():void {
@kumikoono This should be:

```suggestion
  public function assertErrorWarningNotVisible(): void {
```

2022-03-31 08:18 UTC, naoi commented on src/Drupal/DrupalExtension/Context/MessageContext.php
> +  private function assertNotVisible(string $selector_id):void {
@kumikoono This should be:

```suggestion
  private function assertNotVisible(string $selector_id): void {
```

2022-03-31 08:18 UTC, naoi commented on src/Drupal/DrupalExtension/Context/MessageContext.php
> +    }
@kumikoono This should be:

```suggestion
    if (empty($selector_objects)) {
      return;
    }

    $visible_messages = [];
    foreach ($selector_objects as $selector_object) {
      if (empty($selector_object)) {
        continue;
      }
      $visible_messages += $selector_object->getText();
    }
    throw new ExpectationException(sprintf($exception_msg, $this->getSession()->getCurrentUrl(), $selector_id, $visible_messages), $this->getSession()->getDriver());
```

2022-03-31 19:02 UTC, kumikoono commented on src/Drupal/DrupalExtension/Context/MessageContext.php
> +  private function assertNotVisible(string $selector_id):void {
Done

2022-03-31 19:02 UTC, kumikoono commented on src/Drupal/DrupalExtension/Context/MessageContext.php
> +  public function assertErrorWarningNotVisible():void {
Done

2022-03-31 19:03 UTC, kumikoono commented on src/Drupal/DrupalExtension/Context/MessageContext.php
> +    $this->assertNotVisible($selector_id);
Changed to use switch.

2022-03-31 19:03 UTC, kumikoono commented on src/Drupal/DrupalExtension/Context/MessageContext.php
> +    }
Done.

2022-03-31 19:04 UTC, kumikoono commented
Thanks for your review. Updated.

2022-04-01 01:35 UTC, merged